version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    machine: false
    docker:
      - image: node:13-alpine
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t travis-tutorial .
workflows:
  build:
    jobs:
      - build
